# ------------------------------------------------------------
# NookMesh MQTT Broker
# Secure MQTT broker for OwnTracks clients
# TLS encryption + user authentication + ACL authorization
# ------------------------------------------------------------

log_dest stdout
persistence false

# ------------------------------------------------------------
# MQTT listener (TLS)
# ------------------------------------------------------------
listener 8883
protocol mqtt

# ------------------------------------------------------------
# TLS certificates
# ------------------------------------------------------------
cafile /mosquitto/config/cert/RSA-chain.pem
certfile /mosquitto/config/cert/RSA-cert.pem
keyfile /mosquitto/config/cert/RSA-privkey.pem

# ------------------------------------------------------------
# Authentication / Authorization
# ------------------------------------------------------------
allow_anonymous false
password_file /mosquitto/config/generated/mqtt-passwords.txt
acl_file /mosquitto/config/generated/mqtt-acl.txt